### ISSUE TITLE
The resolution of Pix3D

### ISSUE THREAD

**Issue by chirsyes** [ChenHsing/SSP3D#1]
Greets, in your paper, why the resolution of Pix3D is set to $128^3$? In the previous work Pix2Vox++, they mentioned the resolution of voxel in Pix3D is $32^3$, which confused me. Thanks in advance.

**Comment by ChenHsing** [comment]
Follow the paper PADMix in AAAI'22, we set the resolution of Pix3D $128^3$, which shows the effectiveness of our method in high resolution, besides, the origin dataset in Pix3D is   $128^3$. We assume that it is no need to downsample the resolution to  $32^3$, hope it can help you.

**Comment by chirsyes** [comment]
> Follow the paper PADMix in AAAI'22, we set the resolution of Pix3D 1283, which shows the effectiveness of our method in high resolution, besides, the origin dataset in Pix3D is 1283. We assume that it is no need to downsample the resolution to 323, hope it can help you.

Thanks.
