### ISSUE TITLE
Runs with errors！！！

### ISSUE THREAD

**Issue by WFLiu0327** [ChenHsing/SSP3D#2]
[WARNING] 2022-10-23 21:50:19,811 Ignore sample 04530566/c48ed09355e7ab34275e12937d8e1776 since volume file not exists.
[WARNING] 2022-10-23 21:50:19,811 Ignore sample 04530566/d4882179bb3a1868abc6b16fdb345d24 since volume file not exists.
[WARNING] 2022-10-23 21:50:19,811 Ignore sample 04530566/fa63720ea3f8bd379a6e43b878d5b335 since volume file not exists.
[WARNING] 2022-10-23 21:50:19,811 Ignore sample 04530566/54da496566d05afb568b456e2715b08f since volume file not exists.
[WARNING] 2022-10-23 21:50:19,811 Ignore sample 04530566/a88fa5daf540c14a4f6190a680acb783 since volume file not exists.
[INFO] 2022-10-23 21:50:19,811 Complete collecting files of the dataset. Total files: 0.

I followed the readme you gave to put the pix3D datasets into the datasets folder, but it ran with an error, I enjoy your work, can you help me with it, thanks!

**Comment by ChenHsing** [comment]
It seems that your datasets folder path is wrong and load no data. Maybe You can try to redownload the Pix3D dataset follow Pix2Vox.
