### ISSUE TITLE
Memory leak problem

### ISSUE THREAD

**Issue by JiianXue** [ChenHsing/SSP3D#4]
#3 @haoniyang 
hi, i meet the same issues and would like to ask how you solve it. Thank u!

**Comment by ChenHsing** [comment]
I do not meet this issue, maybe it is caused by the dataset code. I would like to recommend you compare it with the code in Pix2Vox(https://github.com/hzxie/Pix2Vox). The main code is based on it.

**Comment by YANGGEOL** [comment]
> #3 @haoniyang hi, i meet the same issues and would like to ask how you solve it. Thank u!

I seem to have encountered a problem similar to yours. Have you solved it?

**Comment by zhihaoyang30** [comment]
I guess you are running the code on a server, you just need to add some plt.close() calls in the functions generating alignment and spectrogram plots.



发自我的iPhone


------------------ Original ------------------
From: yanggeol ***@***.***&gt;
Date: Wed,Mar 20,2024 3:23 PM
To: ChenHsing/SSP3D ***@***.***&gt;
Cc: haoniyang ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [ChenHsing/SSP3D] Memory leak problem (Issue #4)





  
#3 @haoniyang hi, i meet the same issues and would like to ask how you solve it. Thank u!
  
I seem to have encountered a problem similar to yours. Have you solved it?

**Comment by YANGGEOL** [comment]
> I guess you are running the code on a server, you just need to add some plt.close() calls in the functions generating alignment and spectrogram plots. 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: yanggeol ***@***.***&gt; Date: Wed,Mar 20,2024 3:23 PM To: ChenHsing/SSP3D ***@***.***&gt; Cc: haoniyang ***@***.***&gt;, Mention ***@***.***&gt; Subject: Re: [ChenHsing/SSP3D] Memory leak problem (Issue #4) #3 @haoniyang hi, i meet the same issues and would like to ask how you solve it. Thank u! I seem to have encountered a problem similar to yours. Have you solved it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

thank you very much for your help, so I have successfully solved this problem.
